apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wxcc-summarization-gadget
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: gcr.io/digital-is-ops-sandbox-01/wxcc-summarization-gadget:latest
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "8080"
      timeoutSeconds: 300
  traffic:
  - percent: 100